name: Publish Docker Image

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: praekeltorgdeploy
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check Versions
        run: |
            molo_version="$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)"
            docker pull "$IMAGE_NAME" || true
            docker build --pull --tag "$IMAGE_NAME" --build-arg MOLO_VERSION="$molo_version" .
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
